var rgw__sync_8h =
[
    [ "rgw_mdlog_info", "structrgw__mdlog__info.html", "structrgw__mdlog__info" ],
    [ "rgw_mdlog_entry", "structrgw__mdlog__entry.html", "structrgw__mdlog__entry" ],
    [ "rgw_mdlog_shard_data", "structrgw__mdlog__shard__data.html", "structrgw__mdlog__shard__data" ],
    [ "RGWSyncErrorLogger", "class_r_g_w_sync_error_logger.html", "class_r_g_w_sync_error_logger" ],
    [ "rgw_sync_error_info", "structrgw__sync__error__info.html", "structrgw__sync__error__info" ],
    [ "RGWSyncBackoff", "class_r_g_w_sync_backoff.html", "class_r_g_w_sync_backoff" ],
    [ "RGWBackoffControlCR", "class_r_g_w_backoff_control_c_r.html", "class_r_g_w_backoff_control_c_r" ],
    [ "RGWMetaSyncEnv", "struct_r_g_w_meta_sync_env.html", "struct_r_g_w_meta_sync_env" ],
    [ "RGWRemoteMetaLog", "class_r_g_w_remote_meta_log.html", "class_r_g_w_remote_meta_log" ],
    [ "RGWMetaSyncStatusManager", "class_r_g_w_meta_sync_status_manager.html", "class_r_g_w_meta_sync_status_manager" ],
    [ "RGWMetaSyncStatusManager::utime_shard", "struct_r_g_w_meta_sync_status_manager_1_1utime__shard.html", "struct_r_g_w_meta_sync_status_manager_1_1utime__shard" ],
    [ "RGWOrderCallCR", "class_r_g_w_order_call_c_r.html", "class_r_g_w_order_call_c_r" ],
    [ "RGWLastCallerWinsCR", "class_r_g_w_last_caller_wins_c_r.html", "class_r_g_w_last_caller_wins_c_r" ],
    [ "RGWSyncShardMarkerTrack< T, K >", "class_r_g_w_sync_shard_marker_track.html", "class_r_g_w_sync_shard_marker_track" ],
    [ "RGWSyncShardMarkerTrack< T, K >::marker_entry", "struct_r_g_w_sync_shard_marker_track_1_1marker__entry.html", "struct_r_g_w_sync_shard_marker_track_1_1marker__entry" ],
    [ "RGWMetaSyncSingleEntryCR", "class_r_g_w_meta_sync_single_entry_c_r.html", "class_r_g_w_meta_sync_single_entry_c_r" ],
    [ "RGWShardCollectCR", "class_r_g_w_shard_collect_c_r.html", "class_r_g_w_shard_collect_c_r" ],
    [ "DEFAULT_BACKOFF_MAX", "rgw__sync_8h.html#a56083ecd2aed60436aac0efea7f39408", null ],
    [ "ERROR_LOGGER_SHARDS", "rgw__sync_8h.html#ac8a60a8be2db5d0fddffd40fdba3399f", null ],
    [ "RGW_SYNC_ERROR_LOG_SHARD_PREFIX", "rgw__sync_8h.html#ac5f423d1a7806a5f3e8995fa874d51c4", null ],
    [ "create_list_remote_mdlog_shard_cr", "rgw__sync_8h.html#a74787077dd2888098c77f32b4f33bdaf", null ],
    [ "create_read_remote_mdlog_shard_info_cr", "rgw__sync_8h.html#a0f003f5aafe20c2df405154344e0d73e", null ]
];